In [6]:
import pandas as pd

Question 1. Pandas version

In [7]:
pd.__version__

'2.3.3'

Getting the data

In [46]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)

Question 2. Records count

In [47]:
df.shape

(9704, 11)

In [48]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


Question 3. Fuel types

In [50]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

Q4. Missing values

In [51]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [52]:
(df.isnull().sum() > 0).sum()

np.int64(4)

Question 5. Max fuel efficiency

In [53]:
df.loc[df['origin']=='Asia', 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

Question 6. Median value of horsepower

In [54]:
overall_hp_median=df['horsepower'].median()
overall_hp_median

np.float64(149.0)

In [55]:
most_frequent=df['horsepower'].mode()[0]
most_frequent

np.float64(152.0)

In [56]:
df['horsepower']=df['horsepower'].fillna(most_frequent)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           9704 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [57]:
updated_median=df['horsepower'].median()
updated_median

np.float64(152.0)

In [59]:
result = (
    "Yes, it increased" if updated_median > overall_hp_median
    else "Yes, it decreased" if updated_median < overall_hp_median
    else "No"
)
result


'Yes, it increased'

Q7. Sum of weights

In [63]:
asian_cars = df[df['origin']=='Asia']
asian_cars.shape

(3247, 11)

In [69]:
X=asian_cars[['vehicle_weight','model_year']].head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [76]:
import numpy as np
XTX=X.T @ X
XTX_inv= np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [77]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [79]:
w = XTX_inv @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [81]:
sum_w= w.sum()
sum_w

np.float64(0.5187709081074016)